# Generated by Django 5.0 on 2023-12-22 19:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_alter_network_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="date",
            field=models.DateField(
                blank=True, null=True, verbose_name="дата выхода на рынок"
            ),
        ),
    ]
